version: "2.2"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - .:/client
      - /client/node_modules     
    command: npm run start
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - .:/server
      - /server/node_modules  
    command: node ./index.js        
